<?php

namespace EX\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertSkillRepository extends EntityRepository
{
   public function myFindBy(Advert $advert){
       $qb=$this->createQueryBuilder('a')
                ->where('a.advert = :advert')
                    ->setParameter('advert', $advert)
                ->join('a.skill', 's')
                ->addSelect('s');
       
       return $qb->getQuery()->getResult();
   }
}
