<?php

namespace EX\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use InvalidArgumentException;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
  public function getAdverts($nombreParPage,$page)
  {
     
    $query = $this->createQueryBuilder('a')
      ->leftJoin('a.image', 'i')
        ->addSelect('i')
      ->leftJoin('a.categories', 'c')
        ->addSelect('c')
      ->leftJoin('a.advertSkills', 'sa')
        ->addSelect('sa')
      ->leftJoin('sa.skill','s')
        ->addSelect('s')
      ->orderBy('a.date', 'DESC')
      ->getQuery()
    ;
    $query->setFirstResult(($page - 1)*$nombreParPage)
            ->setMaxResults($nombreParPage);
    

    return new Paginator($query, true);
  }
  
 
    public function getAdvertWithCategories(array $categoryNames)
    {
      $qb = $this->createQueryBuilder('a')
              ->join('a.categories', 'c')
              ->addSelect('c');
                    
      
      $qb->where($qb->expr()->in('c.name', $categoryNames));
      
      return $qb->getQuery()
                ->getResult();
      
      
    }
    
   
    
    public function getAdvertByCategory($idCategory){
        $qb = $this->createQueryBuilder('a')
                    ->join('a.categories','c')
                    ->addSelect('c');
        
        $qb->where($qb->expr()->in('c.id',$idCategory));
        
        return $qb->getQuery()->getResult();
    }
    
}
